### ISSUE TITLE
Safari logo issue

### ISSUE THREAD

**Issue by nommaz** [nommaz/hgngrav#6]
PLease see attached screenshot showing size and placement problem in safari. chrome is great (below)

<img width="695" alt="screen shot 2017-03-01 at 06 10 57" src="https://cloud.githubusercontent.com/assets/10116478/23444447/33002020-fe46-11e6-84b3-d98863c9d4f2.png">

**Comment by tranduyhung** [comment]
![screen shot 2560-03-01 at 10 41 32](https://cloud.githubusercontent.com/assets/503262/23445276/e7d07a4c-fe6c-11e6-9684-2347ea19acd6.png)

I don't see that problem here, there should be no problems on Safari because what we changed was just the width and margin-top, there was no special styles which is not compatible with Safari. it seems the browser still serves you the old CSS file, you can try to clear the cache or access sitedomain/user/themes/woo/css/layout.css directly and refresh a few times to force clearing the cache.

**Comment by nommaz** [comment]
my mistake thanks
